#!/bin/bash
###############################################################################
# RagTag Scaffolding of Pigeonpea Genome Assembly
#Author: Muskan
# Description:
# This script uses RagTag to scaffold a polished pigeonpea genome assembly
# against a high-quality reference genome. RagTag performs reference-guided
# scaffolding using minimap2 alignments.
# The same script is used for all the genotypes
# Platform:
#   - Eddie HPC (SGE scheduler)
#
# Input:
#   1. Reference genome (FASTA)
#   2. Polished draft genome assembly (FASTA)
#
# Output:
#   - Scaffolded genome assembly
#   - Alignment and scaffolding reports generated by RagTag
#
# Author: Muskan Sachdeva
###############################################################################

############################
# SGE JOB CONFIGURATION
############################
#$ -N ragtag_3C                   # Job name
#$ -cwd                           # Run in current working directory
#$ -l h_rt=24:00:00               # Maximum runtime (24 hours)
#$ -pe sharedmem 16               # Number of CPU cores requested
#$ -l h_vmem=19G                  # Memory per core (total ~304 GB)
#$ -j y                           # Merge standard output and error
#$ -o ragtag_3C.log               # Log file

############################
# LOAD MODULES & ENVIRONMENT
############################

# Initialise module system
. /etc/profile.d/modules.sh

# Load conda (miniforge) module
module load miniforge

# Activate conda environment containing RagTag
conda activate hifiasm

############################
# RUN RAGTAG SCAFFOLDING
############################

ragtag.py scaffold \
  /exports/eddie/scratch/s2907620/reference/Final_Gapfilled_PPgenome_8FLcontigs.fa \
  /exports/cmvm/eddie/eb/groups/muskan_research/anaconda/envs/hifiasm/nextpolish_results/NSPP_3C/genome.nextpolish.fasta \
  -o /exports/eddie/scratch/s2907620/ragtag/NSPP_3C \
  -C \
  -r \
  --mm2-params "-x asm10"

############################
# NOTES:
# - The reference genome is assumed to be of higher quality and completeness.
# - The '-C' flag enables correction of misassemblies.
# - The '-r' flag removes small contigs not confidently scaffolded.
# - Minimap2 preset 'asm10' is used for assembly-to-assembly alignment.
############################

############################
# END OF SCRIPT
############################
